config:
  # MD013 - Line length (line length is not meaningful inside tables or code blocks)
  MD013:
    line_length: 120
    tables: false
    code_blocks: false
  # MD022 - Headings should be surrounded by blank lines
  MD022: false
  # MD031 - Fenced code blocks should be surrounded by blank lines
  MD031: false
  # MD032 - Lists should be surrounded by blank lines
  MD032: false
  # MD033 - Inline HTML (allow collapsible sections)
  MD033:
    allowed_elements:
      - details
      - summary
  # MD040 - Fenced code blocks should have a language specified
  MD040: false
  # MD060 - Table column style
  MD060: false
